### ISSUE TITLE
Respect form on openEHR inc Version control

### ISSUE THREAD

**Issue by tony-shannon** [RippleOSI/NHS_Ed_Scotland_Open_Platform#8] opened 2019-02-18 10:38 UTC
Hi @freshehr 
Any thoughts about version control here?
We are aware of the current Respect form & expect that will be saved in parts/in total and then revised
We can expect changes to the form over time also..
So how do we handle changes in versions in openEHR ?

FYI @chevalleyc

thanks
T

**Comment by freshehr** [comment] 2019-02-18 16:37
Hi Tony,

I think we did a reasonablr job of getting the Respect team to future-proof the templates once people started to consider the electronic version so I'm hoping that there may not actually be any specific changes required to the actual Respect template itself, though I would suggest we go with an internal version which uses FHIR-aligned versions of some of the demographics archetypes such as organisation, person etc.

Version controlling the template if changes are required is ultimately about maintaining the correct .opt version (at least) in the customer repo. That is the ultimate technical source of truth for Ethercis and I would expect NES to be managing that repo, along with the 'source' archetypes and .oet template.

ok just got to the end of my blurb and realise that you may well be talking about something different i.e incremental changes to the saved data itself. I have nvisaged that we would treat this as a persistent compositiion i.e. after the form is first POST'ed, we will be performing PUTs and essentially overwriting the original data. 

Partial/interim completion of the form might be more tricky. openEHR does support the idea of marking a composition as incomplete but I'm not sure if Ethercis supports this right now and it raises a few tricky issues about how to find it, so it can be finished without it being visible for normal querying. I'd need to discuss with Christian, but argument to leave this out of initial scope.

**Comment by chevalleyc** [comment] 2019-02-19 09:14
Contribution is supported in EtherCIS but not much used at this stage... What is needed is to get it integrated with AQL (e.g. querying on a versioned composition to get the corresponding lifecycle_state. This data is defined in the DB but always set to 'complete' at this stage). I'm not quite sure about the syntax to use to a) set the values of these fields (except for the standard contribution variables and b) what path should we use to query these value points

**Comment by tony-shannon** [comment] 2019-02-19 18:06
> Partial/interim completion of the form might be more tricky. openEHR does support the idea of marking a composition as incomplete but I'm not sure if Ethercis supports this right now and it raises a few tricky issues about how to find it, so it can be finished without it being visible for normal querying. I'd need to discuss with Christian, but argument to leave this out of initial scope.

Indeed thats the tricky bit, I think Christian is saying he can support with some direction?

thanks
T

**Comment by freshehr** [comment] 2019-02-22 10:30
The main issue here is handling 'incomplete/partial' compositions. In the specification, this is left open as to whether it should be handed within the EHR or outside (but part of the CDR). https://specifications.openehr.org/releases/RM/latest/common.html#_version_lifecycle

Certainly other CDR vendors support the idea of draft compositions but I am pretty sure they do not store these inside the EHR object by handling them as a state on the formal composition object but store them outside the EHR but inside the CDR.

That could work but complicates querying as you do not want to find these compositions as part of normal querying. You do of course have to be able to find them in some fashion so they can be completed and formally 'promoted' into the EHR.


Perhaps one for @chevalleyc and I / others to discuss? Doing outside EHR but inside the CDR would be the best approach, I think. We can look at what otherCDR providers do as examples.

**Comment by tony-shannon** [comment] 2019-02-22 14:09
more comments on this from Ian

> Tony: where would that status of complete/incomplete be kept?in openEHR composition terms

> Ian, 11:44 It is inside the versioned composition, however that only becomes important if you try to store inside the EHR. You coud just store them in separate 'draft compositions' table.inside Ethercis but not inside EHR. Probably easier to engineer.but one for CC to decide. The only challenge is that you need to be able to find e.g Respect forms vs. some other incomplete form....
we could simplify that right now just to take some fixed attribute, e.g. the template name or composition name/value.

**Comment by freshehr** [comment] 2019-02-25 12:12
We had a good conversation with clinical leads on this and it is now clear (I think!) that we do not need an 'incomplete/draft composition' in openEHR terms. These would imply that the composition should somehow be regarded as completely invalid and in some fashion hidden from normal use.  The conversation established that the clinical leads would *always* want the saved composition to be visible/available to users, even if it had only been minimally completed. They do want to be able to indicate the level of completion, based on some rules that they will define but will essentially be managed at UI level. We can carry this 'status flag' within the Report composition - I will adjust the template appropriately - @tony-shannon I think we had provisionally agreed "started|incomplete|signed-off" or something like that.

**Comment by tony-shannon** [comment] 2019-03-14 13:14
NB linked to this related/duplicate issue 
ReSPECT form API to OpenEHR inc version control
https://github.com/RippleOSI/NHS_Ed_Scotland_Open_Platform/issues/41

**Comment by freshehr** [comment] 2019-03-16 15:23
**ReSPECT Composition version control:**

1. The initial commit uses a /composition POST call. This will save the composition and generate a unique compoisitonId, including a version suffix

`ab30f532-9645-4a40-b554-5cb5f842a539::hcbox.oprn.ehrscape.com::1` where `::1` is the version suffix.

2. All subsequent updates to the composition should be committed via PUT /composition. This will keep the same composition ID but increment the version suffix.

`ab30f532-9645-4a40-b554-5cb5f842a539::hcbox.oprn.ehrscape.com::2` where `::2` is the version suffix.

3. In normal operation, AQL queries etc will only point to the most recent version of the composition but more sophisticated queries can be used to list previous versions. - see #41 for an example

4. I would suggest the  /composition GET call is used to retrieve the current version of the composition, rather than pulling individual datapoints via AQL as this is fairly complex dataset. This will essentially retrieve the original JSON blob as-was. This should then be updated as appropriate and the updated composition re-commited using a PUT /composition call.

5. Note that it is not possible to retrieve or submit a partial composition, (e.g by section or some other part). indeed it is probably not desirable as working with diffs in these circumstances is prone to error.

6. I suggest that POST/PUT and GET /composition calls make use of the FLAT **OUTPUT** format, and not the usual FLAT **INPUT** format. The OUTPUT format is easier to work with when doing a POST/GET/PUT update cycle as the OUTPUT format matches the structure returned by the GET. - see #41 for details of the format

I would hope that we can manage any changes to the template via non-breaking changes so any data collected will remain compatible but this is a whole other issue really.

**Comment by tony-shannon** [comment] 2019-03-22 09:29
NB linked issues
ReSPECT form API to OpenEHR inc version control #41
https://github.com/RippleOSI/NHS_Ed_Scotland_Open_Platform/issues/41

**Comment by killmenot** [comment] 2019-03-27 19:30
@freshehr 

Have some questions:

1. "All subsequent updates to the composition should be committed via PUT /composition. This will keep the same composition ID but increment the version suffix."
Does it mean that to create a new version I need to call
(1) PUT /composition
or
(2) PUT /composition/{uuid with versionNo +1}

2. When I request "Retrieve ALL versions of Respect composition" I got  error:
#1.0.0 Invocation exception to method:queryInline:java.lang.IllegalArgumentException: Could not interpret field:uid
Details here:
https://gist.github.com/killmenot/74f2157de86dfefe25d83b0b4e137e0c
It looks like "b/uid as version_uid" should be "b/uid/value as version_uid". Is it correct?

3. If (2) is Yes, then "Retrieve ALL versions of Respect composition" and "Retrieve current version of Respect composition" looks very similar. The difference was only in the first line

**Comment by freshehr** [comment] 2019-03-28 11:16
"All subsequent updates to the composition should be committed via PUT /composition. This will keep the same composition ID but increment the version suffix."
Does it mean that to create a new version I need to call

IAN: (2) PUT /composition/{uuid with versionNo +1}

When I request "Retrieve ALL versions of Respect composition" I got error:
#1.0.0 Invocation exception to method:queryInline:java.lang.IllegalArgumentException: Could not interpret field:uid
Details here:
https://gist.github.com/killmenot/74f2157de86dfefe25d83b0b4e137e0c
It looks like "b/uid as version_uid" should be "b/uid/value as version_uid". Is it correct?

If (2) is Yes, then "Retrieve ALL versions of Respect composition" and "Retrieve current version of Respect composition" looks very similar. The difference was only in the first line

Ian: There are some typos / snafus in there - suggest you try the suggestion below - NB not tested but I will do so later.

```
select
  b/uid as compositionUid,
  b/composer/name as authorName,
  b/context/start_time/value as dateUpdated
from EHR e[ehr_id/value = {{ehrId}}] contains
  VERSIONED_OBJECT a contains
  VERSION v[all_versions]
  contains COMPOSITION b
  where b/name/value = 'NSS RESPECT Form'
  ORDER BY b/context/start_time/value DESC
```

#### Retrieve current version of Respect composition:

To retrieve the active version of the Respect composition. Select the first item (should only be one in a production system).

```
select
  b/uid/value as compositionUid,
  b/composer/name as authorName,
  b/context/start_time/value as dateUpdated
from EHR e[ehr_id/value = {{ehrId}}] contains
  contains COMPOSITION b
  where b/name/value = 'NSS RESPECT Form'
  ORDER BY b/context/start_time/value DESC
```

**Comment by freshehr** [comment] 2019-03-28 13:54
Ah - still messed up - these work :)

@killmenot  - now tested and still broken however these work


For list```
select b/uid/value as compositionUid, b/composer/name as authorName, b/context/start_time/value as dateUpdated from EHR e[ehr_id/value = '{{ehrId}}'] contains VERSIONED_OBJECT a contains VERSION v[all_versions] contains COMPOSITION b where b/name/value = 'NSS RESPECT Form' ORDER BY b/context/start_time/value DESC
```
and 

For latest
```
select b/uid/value as compositionUid, b/composer/name as authorName, b/context/start_time/value as dateUpdated from EHR e[ehr_id/value = '{{ehrId}}']  contains COMPOSITION b where b/name/value = 'NSS RESPECT Form' ORDER BY b/context/start_time/value DESC
```

**Comment by freshehr** [comment] 2019-03-28 14:58
Latest updates do run but do not return correct data

https://github.com/ethercis/ethercis/issues/176

https://github.com/ethercis/ethercis/issues/177

**Comment by killmenot** [comment] 2019-03-30 11:15
@freshehr Hi Ian

When do a POST request, I got the following error. Could you please advice how to fix it?
<img width="1307" alt="Screenshot 2019-03-30 14 11 27" src="https://user-images.githubusercontent.com/119337/55275344-da090480-52f5-11e9-8bd1-c657bf540b22.png">

URL:
http://ethercis1.3-test.ripple.foundation:8080/rest/v1/composition?templateId=RESPECT_NSS-v0&format=FLAT&ehrId=7d4039e0-98bf-4a59-9f72-3a9aa4ae677b
Headers:
Content-Type: application/json
Ehr-Session: sessionId:127.0.0.1-guest-1553943810023-763680912-3
Body:
```
{
  "ctx/language": "en",
  "ctx/territory": "GB",
  "nss_respect_form/language|code": "en",
  "nss_respect_form/language|terminology": "ISO_639-1",
  "nss_respect_form/territory|code": "GB",
  "nss_respect_form/territory|terminology": "ISO_3166-1",
  "nss_respect_form/context/_health_care_facility|id": "FV-DGH",
  "nss_respect_form/context/_health_care_facility|id_scheme": "NHSScotland",
  "nss_respect_form/context/_health_care_facility|id_namespace": "NHSScotland",
  "nss_respect_form/context/_health_care_facility|name": "Forth Valley DGH",
  "nss_respect_form/context/start_time": "2019-03-03T23:09:53.121+01:00",
  "nss_respect_form/context/setting|code": "238",
  "nss_respect_form/context/setting|value": "other care",
  "nss_respect_form/context/setting|terminology": "openehr",
  "nss_respect_form/context/status": "",
  "nss_respect_form/composer|name": "Robert Tweed",
  "nss_respect_form/composer|id": "12345",
  "nss_respect_form/composer|id_scheme": "NHSScotland",
  "nss_respect_form/composer|id_namespace": "NHSScotland",
  "nss_respect_form/respect_headings/a2._summary_of_relevant_information/a2.0_relevant_information/respect_summary/narrative_summary": "",
  "nss_respect_form/respect_headings/a3._personal_preferences/preferred_priorities_of_care/patient_care_priority": "",
  "nss_respect_form/respect_headings/a4._clinical_recommendations/recommendation/clinical_focus": "",
  "nss_respect_form/respect_headings/a4._clinical_recommendations/recommendation/clinical_guidance_on_interventions": "",
  "nss_respect_form/respect_headings/a4._clinical_recommendations/cpr_decision/cpr_decision|code": "",
  "nss_respect_form/respect_headings/a4._clinical_recommendations/cpr_decision/date_of_cpr_decision": "2019-03-03T23:09:53.121+01:00",
  "nss_respect_form/respect_headings/a5._capacity_and_representation/capacity_respect/sufficient_capacity": "Error running: toBoolean('')",
  "nss_respect_form/respect_headings/a5._capacity_and_representation/capacity_respect/legal_proxy|code": "",
  "nss_respect_form/respect_headings/a6._involvement_in_making_plan/involvement_respect/involvement_in_recommendations/involvement|code": "",
  "nss_respect_form/respect_headings/a6._involvement_in_making_plan/involvement_respect/involvement_in_recommendations/reason_for_not_selecting_options_a_or_b_or_c": "",
  "nss_respect_form/respect_headings/a6._involvement_in_making_plan/involvement_respect/name_and_role_of_those_involved_in_decision_making": "",
  "nss_respect_form/respect_headings/a7._clinician_signatures/clinician_signature:0/ism_transition/current_state|value": "completed",
  "nss_respect_form/respect_headings/a7._clinician_signatures/clinician_signature:0/service_name": "ReSPECT clinician signature",
  "nss_respect_form/respect_headings/a7._clinician_signatures/clinician_signature:0/signing_clinician/practitioner_role/designation": "",
  "nss_respect_form/respect_headings/a7._clinician_signatures/clinician_signature:0/signing_clinician/name/use|code": "at0002",
  "nss_respect_form/respect_headings/a7._clinician_signatures/clinician_signature:0/signing_clinician/text": "",
  "nss_respect_form/respect_headings/a7._clinician_signatures/clinician_signature:0/signing_clinician/identifier/value": "",
  "nss_respect_form/respect_headings/a7._clinician_signatures/clinician_signature:0/signing_clinician/identifier/value|issuer": "ProfessionalID",
  "nss_respect_form/respect_headings/a7._clinician_signatures/clinician_signature:0/signing_clinician/identifier/value|assigner": "ProfessionalID",
  "nss_respect_form/respect_headings/a7._clinician_signatures/clinician_signature:0/signing_clinician:0/identifier/value|type": "ProfessionalID",
  "nss_respect_form/respect_headings/a7._clinician_signatures/clinician_signature:0/signing_clinician:0/identifier/use|code": "at0004",
  "nss_respect_form/respect_headings/a7._clinician_signatures/clinician_signature:0/time": "2019-03-03T23:09:53.121+01:00",
  "nss_respect_form/respect_headings/a8._emergency_contacts/emergency_contacts/name": "ReSPECT emergency contacts",
  "nss_respect_form/respect_headings/a8._emergency_contacts/emergency_contacts/participant:0/role": "",
  "nss_respect_form/respect_headings/a8._emergency_contacts/emergency_contacts/participant:0/contact/name/use|code": "",
  "nss_respect_form/respect_headings/a8._emergency_contacts/emergency_contacts/participant:0/contact/name:0/text": "",
  "nss_respect_form/respect_headings/a8._emergency_contacts/emergency_contacts/participant:0/contact/telephone/system|code": "",
  "nss_respect_form/respect_headings/a8._emergency_contacts/emergency_contacts/participant:0/contact/telephone/telephone_number": "",
  "nss_respect_form/respect_headings/a8._emergency_contacts/emergency_contacts/other_details": "",
  "nss_respect_form/respect_headings/a9._confirmation_of_validity/service:0/ism_transition/current_state|value": "completed",
  
  "nss_respect_form/respect_headings/a9._confirmation_of_validity/service:0/responsible_clinician/practitioner_role/designation": "",
  "nss_respect_form/respect_headings/a9._confirmation_of_validity/service:0/responsible_clinician/name/use|code": "",
  "nss_respect_form/respect_headings/a9._confirmation_of_validity/service:0/responsible_clinician/name/text": "",
  "nss_respect_form/respect_headings/a9._confirmation_of_validity/service:0/responsible_clinician/identifier/value": "",
  "nss_respect_form/respect_headings/a9._confirmation_of_validity/service:0/responsible_clinician/identifier/value|issuer": "ProfessionalID",
  "nss_respect_form/respect_headings/a9._confirmation_of_validity/service:0/responsible_clinician/identifier/value|assigner": "ProfessionalID",
  "nss_respect_form/respect_headings/a9._confirmation_of_validity/service:0/responsible_clinician/identifier/value|type": "ProfessionalID",
  "nss_respect_form/respect_headings/a9._confirmation_of_validity/service:0/responsible_clinician/identifier/use|code": "at0004",
  "nss_respect_form/respect_headings/a9._confirmation_of_validity/service:0/review_date": "",
  "nss_respect_form/respect_headings/a9._confirmation_of_validity/service:0/time": "2019-03-03T23:09:53.121+01:00"
}
```

Note:
I removed this line
```
"nss_respect_form/respect_headings/a9._confirmation_of_validity/service:0/ism_transition/service_name": "Respect form - confirmation of validity",
```
because I got the following when it was added to the payload:
```
 #1.0.0 Invocation exception to method:create:java.lang.IllegalArgumentException: Could not convert JSON map:com.marand.thinkehr.f.b.b.a: Unknown segment: service_name! (path: nss_respect_form/respect_headings/a9._confirmation_of_validity/service:0/ism_transition/service_name)
```

**Comment by killmenot** [comment] 2019-03-30 11:21
@freshehr seems I need to omit "format=FLAT" parameter to have the query above working :) Weird but others headings use it...

**Comment by freshehr** [comment] 2019-03-30 16:54
@killmenot ...

The line you removed has a typo. It should be 
```
"nss_respect_form/respect_headings/a9._confirmation_of_validity/service:0/service_name": "Respect form - confirmation of validity",
```

However, you will still get errors because if you add an identifier object, the id is mandatory..
 e.g you had 

```
  "nss_respect_form/respect_headings/a7._clinician_signatures/clinician_signature:0/signing_clinician/identifier/value": "",
  "nss_respect_form/respect_headings/a7._clinician_signatures/clinician_signature:0/signing_clinician/identifier/value|issuer": "ProfessionalID",
  "nss_respect_form/respect_headings/a7._clinician_signatures/clinician_signature:0/signing_clinician/identifier/value|assigner": "ProfessionalID",
  "nss_respect_form/respect_headings/a7._clinician_signatures/clinician_signature:0/signing_clinician:0/identifier/value|type": "ProfessionalID",
  "nss_respect_form/respect_headings/a7._clinician_signatures/clinician_signature:0/signing_clinician:0/identifier/use|code": "at0004",
```
but it needs to be
``` "nss_respect_form/respect_headings/a7._clinician_signatures/clinician_signature:0/signing_clinician/identifier/value": "123456789",
  "nss_respect_form/respect_headings/a7._clinician_signatures/clinician_signature:0/signing_clinician/identifier/value|issuer": "ProfessionalID",
  "nss_respect_form/respect_headings/a7._clinician_signatures/clinician_signature:0/signing_clinician/identifier/value|assigner": "ProfessionalID",
  "nss_respect_form/respect_headings/a7._clinician_signatures/clinician_signature:0/signing_clinician:0/identifier/value|type": "ProfessionalID",
  "nss_respect_form/respect_headings/a7._clinician_signatures/clinician_signature:0/signing_clinician:0/identifier/use|code": "at0004",
```
If the id value is not available you should not try to send a partial identifier object i.e this should work, because th ewhole identifier object is itself optional.

```
"nss_respect_form/respect_headings/a7._clinician_signatures/clinician_signature:0/signing_clinician/text": "",
```  

Working example  (on ThinkEHr... and Ethercis)
```
{
  "ctx/language": "en",
  "ctx/territory": "GB",
  "nss_respect_form/language|code": "en",
  "nss_respect_form/language|terminology": "ISO_639-1",
  "nss_respect_form/territory|code": "GB",
  "nss_respect_form/territory|terminology": "ISO_3166-1",
  "nss_respect_form/context/_health_care_facility|id": "FV-DGH",
  "nss_respect_form/context/_health_care_facility|id_scheme": "NHSScotland",
  "nss_respect_form/context/_health_care_facility|id_namespace": "NHSScotland",
  "nss_respect_form/context/_health_care_facility|name": "Forth Valley DGH",
  "nss_respect_form/context/start_time": "2019-03-03T23:09:53.121+01:00",
  "nss_respect_form/context/setting|code": "238",
  "nss_respect_form/context/setting|value": "other care",
  "nss_respect_form/context/setting|terminology": "openehr",
  "nss_respect_form/context/status": "",
  "nss_respect_form/composer|name": "Robert Tweed",
  "nss_respect_form/composer|id": "12345",
  "nss_respect_form/composer|id_scheme": "NHSScotland",
  "nss_respect_form/composer|id_namespace": "NHSScotland",
  "nss_respect_form/respect_headings/a2._summary_of_relevant_information/a2.0_relevant_information/respect_summary/narrative_summary": "",
  "nss_respect_form/respect_headings/a3._personal_preferences/preferred_priorities_of_care/patient_care_priority": "",
  "nss_respect_form/respect_headings/a4._clinical_recommendations/recommendation/clinical_focus": "",
  "nss_respect_form/respect_headings/a4._clinical_recommendations/recommendation/clinical_guidance_on_interventions": "",
  "nss_respect_form/respect_headings/a4._clinical_recommendations/cpr_decision/cpr_decision|code": "",
  "nss_respect_form/respect_headings/a4._clinical_recommendations/cpr_decision/date_of_cpr_decision": "2019-03-03T23:09:53.121+01:00",
  "nss_respect_form/respect_headings/a5._capacity_and_representation/capacity_respect/sufficient_capacity": "Error running: toBoolean('')",
  "nss_respect_form/respect_headings/a5._capacity_and_representation/capacity_respect/legal_proxy|code": "",
  "nss_respect_form/respect_headings/a6._involvement_in_making_plan/involvement_respect/involvement_in_recommendations/involvement|code": "",
  "nss_respect_form/respect_headings/a6._involvement_in_making_plan/involvement_respect/involvement_in_recommendations/reason_for_not_selecting_options_a_or_b_or_c": "",
  "nss_respect_form/respect_headings/a6._involvement_in_making_plan/involvement_respect/name_and_role_of_those_involved_in_decision_making": "",
  "nss_respect_form/respect_headings/a7._clinician_signatures/clinician_signature:0/ism_transition/current_state|value": "completed",
  "nss_respect_form/respect_headings/a7._clinician_signatures/clinician_signature:0/service_name": "ReSPECT clinician signature",
  "nss_respect_form/respect_headings/a7._clinician_signatures/clinician_signature:0/signing_clinician/practitioner_role/designation": "",
  "nss_respect_form/respect_headings/a7._clinician_signatures/clinician_signature:0/signing_clinician/name/use|code": "at0002",
  "nss_respect_form/respect_headings/a7._clinician_signatures/clinician_signature:0/signing_clinician/text": "",
  "nss_respect_form/respect_headings/a7._clinician_signatures/clinician_signature:0/signing_clinician/identifier/value": "1234",
  "nss_respect_form/respect_headings/a7._clinician_signatures/clinician_signature:0/signing_clinician/identifier/value|issuer": "ProfessionalID",
  "nss_respect_form/respect_headings/a7._clinician_signatures/clinician_signature:0/signing_clinician/identifier/value|assigner": "ProfessionalID",
  "nss_respect_form/respect_headings/a7._clinician_signatures/clinician_signature:0/signing_clinician:0/identifier/value|type": "ProfessionalID",
  "nss_respect_form/respect_headings/a7._clinician_signatures/clinician_signature:0/signing_clinician:0/identifier/use|code": "at0004",
  "nss_respect_form/respect_headings/a7._clinician_signatures/clinician_signature:0/time": "2019-03-03T23:09:53.121+01:00",
  "nss_respect_form/respect_headings/a8._emergency_contacts/emergency_contacts/name": "ReSPECT emergency contacts",
  "nss_respect_form/respect_headings/a8._emergency_contacts/emergency_contacts/participant:0/role": "",
  "nss_respect_form/respect_headings/a8._emergency_contacts/emergency_contacts/participant:0/contact/name/use|code": "",
  "nss_respect_form/respect_headings/a8._emergency_contacts/emergency_contacts/participant:0/contact/name:0/text": "",
  "nss_respect_form/respect_headings/a8._emergency_contacts/emergency_contacts/participant:0/contact/telephone/system|code": "",
  "nss_respect_form/respect_headings/a8._emergency_contacts/emergency_contacts/participant:0/contact/telephone/telephone_number": "",
  "nss_respect_form/respect_headings/a8._emergency_contacts/emergency_contacts/other_details": "",
  "nss_respect_form/respect_headings/a9._confirmation_of_validity/service:0/service_name": "Respect form - confirmation of validity",
  "nss_respect_form/respect_headings/a9._confirmation_of_validity/service:0/ism_transition/current_state|value": "completed",
  
  "nss_respect_form/respect_headings/a9._confirmation_of_validity/service:0/responsible_clinician/practitioner_role/designation": "",
  "nss_respect_form/respect_headings/a9._confirmation_of_validity/service:0/responsible_clinician/name/use|code": "",
  "nss_respect_form/respect_headings/a9._confirmation_of_validity/service:0/responsible_clinician/name/text": "",
  "nss_respect_form/respect_headings/a9._confirmation_of_validity/service:0/responsible_clinician/identifier/value": "1234",
  "nss_respect_form/respect_headings/a9._confirmation_of_validity/service:0/responsible_clinician/identifier/value|issuer": "ProfessionalID",
  "nss_respect_form/respect_headings/a9._confirmation_of_validity/service:0/responsible_clinician/identifier/value|assigner": "ProfessionalID",
  "nss_respect_form/respect_headings/a9._confirmation_of_validity/service:0/responsible_clinician/identifier/value|type": "ProfessionalID",
  "nss_respect_form/respect_headings/a9._confirmation_of_validity/service:0/responsible_clinician/identifier/use|code": "at0004",
  "nss_respect_form/respect_headings/a9._confirmation_of_validity/service:0/review_date": "",
  "nss_respect_form/respect_headings/a9._confirmation_of_validity/service:0/time": "2019-03-03T23:09:53.121+01:00"
}
```

**Comment by killmenot** [comment] 2019-04-02 10:29
@freshehr 

Could you please take a look?
https://gist.github.com/killmenot/78ade6c1be0cc789c969afdea9bad021

1. By some reason, when I do the PUT request, it returns me result with first version but meta prop contains the second version (line 16)
2. When I do a GET request with the second version, I got error (line 93)

Or did I do something wrong?

**Comment by freshehr** [comment] 2019-04-02 10:34
This one is for @chevalleyc - I thought this had been fixed. The calls that you are making look correct to me. @chevalleyc - it looks as if composition version incrementing is still problematic

**Comment by freshehr** [comment] 2019-04-02 10:45
@killmenot - the PUT call needs to carry the **previous** version of the compositionUid

```
i.e 

```
PUT http://ethercis1.3-test.ripple.foundation:8080/rest/v1/composition/98df5b17-4ff2-4e43-b0db-e42414d595c0::nes.ripple.foundation::1?templateId=RESPECT_NSS-v0
```
and not 

``
PUT http://ethercis1.3-test.ripple.foundation:8080/rest/v1/composition/98df5b17-4ff2-4e43-b0db-e42414d595c0::nes.ripple.foundation::2?templateId=RESPECT_NSS-v0
```

**Comment by killmenot** [comment] 2019-04-13 15:05
@freshehr 

Looks like different queries return me the same result:

#### LIST
Query:
```
select
    b/uid/value as compositionUid,
    b/composer/name as authorName,
    b/context/start_time/value as dateUpdated
from EHR e[ehr_id/value = '91faff0b-cb5d-4f93-bf37-a99165aba439']
    contains VERSIONED_OBJECT a
    contains VERSION v[all_versions]
    contains COMPOSITION b
where b/name/value = 'NSS RESPECT Form'
ORDER BY b/context/start_time/value DESC
```
Result:
<img width="1329" alt="Screenshot 2019-04-13 18 03 47" src="https://user-images.githubusercontent.com/119337/56081476-84187e80-5e16-11e9-9252-c89896ec55d1.png">

#### Latest
Query:
```
select
    b/uid/value as compositionUid,
    b/composer/name as authorName,
    b/context/start_time/value as dateUpdated
from EHR e[ehr_id/value = '91faff0b-cb5d-4f93-bf37-a99165aba439']
    contains COMPOSITION b
where b/name/value = 'NSS RESPECT Form'
    ORDER BY b/context/start_time/value DESC
```

Result:
<img width="1378" alt="Screenshot 2019-04-13 18 04 58" src="https://user-images.githubusercontent.com/119337/56081489-a8745b00-5e16-11e9-8a4d-8468b50c370c.png">

Is it expected behaviour?

**Comment by freshehr** [comment] 2019-04-13 15:51
@killmenot - To retreive the full kist of previous versions  - See https://github.com/ethercis/ethercis/issues/175#issuecomment-479305569

You will have to use/adapt the SQL statement that @chevalleyc has advised. I will have a little more time tomorrow to advise further - note that you need to send {"sql" : "..."} in the body not {"aql" :"..."}

**Comment by killmenot** [comment] 2019-04-13 16:06
```
note that you need to send {"sql" : "..."} in the body not {"aql" :"..."}
```
@freshehr Does the advice above work for respectforms only or for all requests to headings?

**Comment by freshehr** [comment] 2019-04-13 16:15
@killmenot - should work for all - just change the uid

**Comment by tony-shannon** [comment] 2019-04-15 12:30
update by email

posted also to #57 

Update by email between @killmenot and @BogdanScherban 

> Hi Bogdan,
> 
> I've updated my version of code but there are some problems with mapping logic + I have some questions for teammates. I need a couple of days to resolve these issues.
> In the meantime, you can work with this version of the code:
> https://github.com/killmenot/QEWD-Courier/tree/develop-respectforms
> Please ask @Dmitry to help you with deploy if you haven't done it yet.
> 
> 1. GET /api/patients/:patientId/respectforms
> Sample of data returned: https://gist.github.com/killmenot/32bb81ddf68256341529e06864d11a12
> NOTES: 
>  - "status" prop's value seems incorrect. I'll fix it soon.
> 
> 2. GET /api/patients/:patientId/respectforms/:sourceId/:version
> Sample of data returned: https://gist.github.com/killmenot/1c5e77b2f37a997094190b090d9a2144
> NOTES:
>  -  Please ignore "status" and "dateCompleted" props in nested objects. They are hardcoded now
>  -  Some of props (such as "summaryInformation", "personalPreferences", etc...) can be undefined because when a form version can be created without any props (I'll clarify this moment).
> 
> 3. POST /api/patients/:patientId/respectforms
> You can skip passing data here but if you need to pass anything to API, it expects "data.respect_form" from (2) above
> NOTES:
>  - Currently, it doesn't return correct response by spec:
> https://docs.google.com/document/d/1-EXxplkEPG8OckYzx085164_E5_g4DbZS0FQ0dRqZ7c/edit
> 
> 4. Please note that "emergencyContacts.contactsArray", "confirmation.confirmationsArray", "clinicalSignatures.signaturesArray" can contain and should return multiple items
> 
> 5. clinicalRecommendation.cprValue can be "CPRRecommended", "NotforCPR", "ModifiedCPR" or "N/A" 
> 6. capacityAndRepresentation.legalProxyValue can be "Yes", "No", "Unknown" and "N/A"
> 7. involvement.involvementValue can be "valueSetA", "valueSetB", "valueSetC1", "valueSetC1", "valueSetC2", "valueSetC3", "valueSetD"
> Note: I can update "N/A" to any value you need. it's a value by default if no code match (@Tony  - ???)
> 
> @ALL
> Tomorrow, I will ask questions I have about respectforms logic and methods and continue with POST/PUT methods. Unit tests for respectforms logic are currently disabled or haven't written but I will take care about them on Wednesday
> 
> 
> 
> On Tue, Apr 9, 2019 at 2:03 PM Alexey Kucherenko  wrote:
> P.S.
> develop+respectforms (db version) merged here
> https://github.com/killmenot/QEWD-Courier/tree/develop-respectforms
> so I will work with this branch and then reopen PR
>

**Closed as completed** 2019-05-02 08:09 UTC
Labels: NES, EtherCIS
