### ISSUE TITLE
When create very first Version, creates 2 versions

### ISSUE THREAD

**Issue by kuvakina** [RippleOSI/NHS_Ed_Scotland_Open_Platform#79] opened 2019-04-23 17:48 UTC
When create very first Version it create 2 versions: first is empty and second with info that was filled in. 

See the video:
https://drive.google.com/file/d/1Om4SuG4yg3vKT0smF5173R5PqYCeil82/view

**Comment by PhilBarrett** [comment] 2019-05-02 08:11
Duplicate of #91, closing

**Closed as completed by PhilBarrett** 2019-05-02 08:11 UTC
Labels: NES, PulseTile-RA
